services:
  plutor-db:
    image: postgres:17.5
    container_name: plutor-db
    environment:
      POSTGRES_USER: plutor_user
      POSTGRES_PASSWORD: secure_password
      POSTGRES_DB: plutor_db
    ports:
      - "54320:5432"
    volumes:
      - plutor_db_data:/var/lib/postgresql/data
    networks:
      - plutor-network

volumes:
  plutor_db_data:

networks:
  plutor-network: